In [75]:
'''
import os
if not os.path.exists('exchange_rate_analysis'):
    !git clone https://github.com/matthewhirokawa/exchange_rate_analysis.git
%cd exchange_rate_analysis
'''

"\nimport os\nif not os.path.exists('exchange_rate_analysis'):\n    !git clone https://github.com/matthewhirokawa/exchange_rate_analysis.git\n%cd exchange_rate_analysis\n"

In [76]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn.metrics import mean_squared_error, r2_score

In [77]:
monthly_sentiment_nltk = pd.read_csv('data/usa_china_extended_monthly_sentiment_nltk.csv')
#monthly_sentiment_nltk['Month'] = pd.to_datetime(monthly_sentiment_nltk['Month']).dt.to_period('M')

monthly_sentiment_textblob = pd.read_csv('data/usa_china_extended_monthly_sentiment_textblob.csv')
#monthly_sentiment_textblob['Month'] = pd.to_datetime(monthly_sentiment_textblob['Month']).dt.to_period('M')
monthly_sentiment_textblob.head()

     Month   Relation  Sentiment
0  2021-01  USA-China   0.023501
1  2021-02  USA-China   0.020157
2  2021-03  USA-China   0.010724
3  2021-04  USA-China   0.014211
4  2021-05  USA-China   0.009114

In [78]:
usd_cny_exchange_rate = pd.read_csv('data/usd_cny_monthly_exchange_rate_2021.csv')
#usd_cny_exchange_rate['Month'] = pd.to_datetime(usd_cny_exchange_rate['Month']).dt.to_period('M')
usd_cny_exchange_rate.head()

         DATE  EXCHUS    Month
0  2021-01-01  6.4672  2021-01
1  2021-02-01  6.4601  2021-02
2  2021-03-01  6.5109  2021-03
3  2021-04-01  6.5186  2021-04
4  2021-05-01  6.4321  2021-05

In [79]:
#combine dataframes, drop date keep month
combined_df_textblob = pd.merge(monthly_sentiment_textblob, usd_cny_exchange_rate, on = 'Month', how = 'inner')
combined_df_textblob = combined_df_textblob.drop(columns=['DATE'])
#combined_df_textblob.to_csv("combined_df_textblob.csv", index = False)
combined_df_textblob.head()

     Month   Relation  Sentiment  EXCHUS
0  2021-01  USA-China   0.023501  6.4672
1  2021-02  USA-China   0.020157  6.4601
2  2021-03  USA-China   0.010724  6.5109
3  2021-04  USA-China   0.014211  6.5186
4  2021-05  USA-China   0.009114  6.4321

In [80]:
#create linear regression
df = pd.read_csv('data/combined_df_textblob.csv', index_col = False)
df = df.dropna()

y = df['Log_EXCHUS_Lag']
x = df[['Sentiment_Change']]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

model = LinearRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Test MSE:", mse)
print("Test R-squared:", r2)
print("Model coefficient:", model.coef_[0])
print("Model intercept:", model.intercept_)

df.head()

Test MSE: 0.00013004019210459397
Test R-squared: -0.045083615802483656
Model coefficient: -0.06998869326199071
Model intercept: 0.0023479349016223934

,Month,Relation,Sentiment,EXCHUS,Log_EXCHUS,Log_Sentiment,Sentiment_Change,Log_EXCHUS_Lag
1,2021-02,USA-China,0.020157,6.4601,-0.001098,-0.153487936,-0.003344,0.007833
2,2021-03,USA-China,0.010724,6.5109,0.007833,-0.63106134,-0.009433,0.001182
3,2021-04,USA-China,0.014211,6.5186,0.001182,0.281525595,0.003487,-0.013359
4,2021-05,USA-China,0.009114,6.4321,-0.013359,-0.444211891,-0.005097,-0.001104
5,2021-06,USA-China,0.008897,6.4250,-0.001104,-0.024057627,-0.000217,0.007953

In [81]:
#model summary of sentiment and log exchange rate, lagged by 1 period
x = df[['Sentiment_Change']]

# Add constant (intercept) term
x = sm.add_constant(x)

# Dependent variable
y = df['Log_EXCHUS_Lag']

# Fit the OLS model
model = sm.OLS(y, x).fit()

# Print the summary
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         Log_EXCHUS_Lag   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.019
Method:                 Least Squares   F-statistic:                   0.03007
Date:                Mon, 04 Aug 2025   Prob (F-statistic):              0.863
Time:                        11:08:23   Log-Likelihood:                 155.68
No. Observations:                  52   AIC:                            -307.4
Df Residuals:                      50   BIC:                            -303.5
Df Model:                           1
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0020      0.002      1.181      0.243      -0.001       0.005
Sentiment_Change    -0.0285      0.164     -0.173      0.863      -0.359       0.302
==============================================================================
Omnibus:                        7.734   Durbin-Watson:                   1.183
Prob(Omnibus):                  0.021   Jarque-Bera (JB):                9.806
Skew:                           0.462   Prob(JB):                      0.00743
Kurtosis:                       4.917   Cond. No.                         96.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [113]:
#read in extra data from excel
df = pd.read_csv('data/multi_regression.csv', index_col = False)
df = df.dropna()
df.head()

,Month,Relation,Sentiment,EXCHUS,US_tariff_rate,China_tariff_rate,US_exports_millions,China_exports_millions,Trade_balance,Log_EXCHUS_Change,Sentiment_Change,Log_EXCHUS_Change_Lag,US_log_tariff_rate_change_lag,China_log_tariff_rate_change_lag,Trade_balance_change_lag,US_log_exports_change_lag,China_log_exports_change_lag,US_log_exports_change,China_log_exports_change,Sentiment_change_lag
1,2021-02,USA-China,0.020157,6.4601,19.3,21.1,9265.1,33816.8,-24551.7,-0.001098,-0.003344,0.007833,0.0,0.0,-2570.3,0.324128,0.166270,-0.339556,-0.138372,-0.009433
2,2021-03,USA-China,0.010724,6.5109,19.3,21.1,12812.0,39934.0,-27122.0,0.007833,-0.009433,0.001182,0.0,0.0,1682.3,-0.071209,-0.066330,0.324128,0.166270,0.003487
3,2021-04,USA-China,0.014211,6.5186,19.3,21.1,11931.4,37371.1,-25439.7,0.001182,0.003487,-0.013359,0.0,0.0,-639.4,0.039119,0.029410,-0.071209,-0.066330,-0.005097
4,2021-05,USA-China,0.009114,6.4321,19.3,21.1,12407.4,38486.5,-26079.1,-0.013359,-0.005097,-0.001104,0.0,0.0,-1557.6,-0.021573,0.033039,0.039119,0.029410,-0.000217
5,2021-06,USA-China,0.008897,6.4250,19.3,21.1,12142.6,39779.3,-27636.7,-0.001104,-0.000217,0.007953,0.0,0.0,-896.9,-0.032246,0.012779,-0.021573,0.033039,0.004191

In [115]:
#run multiregression with flipped x and y to check relationships
y = df['Sentiment_Change']
#x = df[['Log_EXCHUS_Change_Lag', 'US_log_tariff_rate_change_lag', 'China_log_tariff_rate_change_lag', 'US_log_exports_change_lag', 'China_log_exports_change_lag']]
x = df[['Log_EXCHUS_Change_Lag', 'US_log_tariff_rate_change_lag', 'China_log_tariff_rate_change_lag', 'Trade_balance_change_lag']]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

model = LinearRegression()
model.fit(x_train, y_train)

# Add constant (intercept) term
x = sm.add_constant(x)
# Fit the OLS model
model = sm.OLS(y, x).fit()

# Print the summary
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       Sentiment_Change   R-squared:                       0.017
Model:                            OLS   Adj. R-squared:                 -0.069
Method:                 Least Squares   F-statistic:                    0.1974
Date:                Mon, 04 Aug 2025   Prob (F-statistic):              0.938
Time:                        11:21:58   Log-Likelihood:                 160.63
No. Observations:                  51   AIC:                            -311.3
Df Residuals:                      46   BIC:                            -301.6
Df Model:                           4
Covariance Type:            nonrobust
====================================================================================================
                                       coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------
const                               -0.0004      0.002     -0.248      0.805      -0.004       0.003
Log_EXCHUS_Change_Lag               -0.0263      0.127     -0.208      0.836      -0.282       0.229
US_log_tariff_rate_change_lag       -0.0029      0.020     -0.144      0.886      -0.044       0.038
China_log_tariff_rate_change_lag     0.0029      0.012      0.251      0.803      -0.021       0.026
Trade_balance_change_lag          3.325e-07   3.98e-07      0.834      0.408    -4.7e-07    1.13e-06
==============================================================================
Omnibus:                       15.565   Durbin-Watson:                   3.048
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               21.738
Skew:                           1.018   Prob(JB):                     1.90e-05
Kurtosis:                       5.467   Cond. No.                     3.20e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.2e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [119]:
#run regression of only sentiment change and US export change, export change is dependent variable
x = df[['Sentiment_Change']]
y = df['US_log_exports_change_lag']

#y = df['Trade_balance_change_lag']

# Add constant (intercept) term
x = sm.add_constant(x)
# Fit the OLS model
model = sm.OLS(y, x).fit()

# Print the summary
print(model.summary())

                                OLS Regression Results
=====================================================================================
Dep. Variable:     US_log_exports_change_lag   R-squared:                       0.079
Model:                                   OLS   Adj. R-squared:                  0.060
Method:                        Least Squares   F-statistic:                     4.187
Date:                       Mon, 04 Aug 2025   Prob (F-statistic):             0.0461
Time:                               11:22:44   Log-Likelihood:                 29.141
No. Observations:                         51   AIC:                            -54.28
Df Residuals:                             49   BIC:                            -50.42
Df Model:                                  1
Covariance Type:                   nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const               -0.0052      0.020     -0.267      0.790      -0.044       0.034
Sentiment_Change     3.8184      1.866      2.046      0.046       0.068       7.568
==============================================================================
Omnibus:                        3.317   Durbin-Watson:                   1.850
Prob(Omnibus):                  0.190   Jarque-Bera (JB):                2.287
Skew:                           0.442   Prob(JB):                        0.319
Kurtosis:                       3.543   Cond. No.                         95.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.