In [1]:
import os
if not os.path.exists('exchange_rate_analysis'):
    !git clone https://github.com/matthewhirokawa/exchange_rate_analysis.git
%cd exchange_rate_analysis

"\nimport os\nif not os.path.exists('exchange_rate_analysis'):\n    !git clone https://github.com/matthewhirokawa/exchange_rate_analysis.git\n%cd exchange_rate_analysis\n"

In [2]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
monthly_sentiment_nltk = pd.read_csv('data/usa_china_extended_monthly_sentiment_nltk.csv')
#monthly_sentiment_nltk['Month'] = pd.to_datetime(monthly_sentiment_nltk['Month']).dt.to_period('M')

monthly_sentiment_textblob = pd.read_csv('data/usa_china_extended_monthly_sentiment_textblob.csv')
#monthly_sentiment_textblob['Month'] = pd.to_datetime(monthly_sentiment_textblob['Month']).dt.to_period('M')
monthly_sentiment_textblob.head()

     Month   Relation  Sentiment
0  2021-01  USA-China   0.023501
1  2021-02  USA-China   0.020157
2  2021-03  USA-China   0.010724
3  2021-04  USA-China   0.014211
4  2021-05  USA-China   0.009114

In [4]:
usd_cny_exchange_rate = pd.read_csv('data/usd_cny_monthly_exchange_rate_2021.csv')
#usd_cny_exchange_rate['Month'] = pd.to_datetime(usd_cny_exchange_rate['Month']).dt.to_period('M')
usd_cny_exchange_rate.head()

         DATE  EXCHUS    Month
0  2021-01-01  6.4672  2021-01
1  2021-02-01  6.4601  2021-02
2  2021-03-01  6.5109  2021-03
3  2021-04-01  6.5186  2021-04
4  2021-05-01  6.4321  2021-05

In [5]:
#combine dataframes, drop date keep month
combined_df_textblob = pd.merge(monthly_sentiment_textblob, usd_cny_exchange_rate, on = 'Month', how = 'inner')
combined_df_textblob = combined_df_textblob.drop(columns=['DATE'])
#combined_df_textblob.to_csv("combined_df_textblob.csv", index = False)
combined_df_textblob.head()

     Month   Relation  Sentiment  EXCHUS
0  2021-01  USA-China   0.023501  6.4672
1  2021-02  USA-China   0.020157  6.4601
2  2021-03  USA-China   0.010724  6.5109
3  2021-04  USA-China   0.014211  6.5186
4  2021-05  USA-China   0.009114  6.4321

In [6]:
#create linear regression
df = pd.read_csv('data/combined_df_textblob.csv', index_col = False)
df = df.dropna()

y = df['Log_EXCHUS_Lag']
x = df[['Sentiment_Change']]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

model = LinearRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Test MSE:", mse)
print("Test R-squared:", r2)
print("Model coefficient:", model.coef_[0])
print("Model intercept:", model.intercept_)

df.head()

Test MSE: 0.00013004019210459397
Test R-squared: -0.045083615802483656
Model coefficient: -0.06998869326199071
Model intercept: 0.0023479349016223934

,Month,Relation,Sentiment,EXCHUS,Log_EXCHUS,Log_Sentiment,Sentiment_Change,Log_EXCHUS_Lag
1,2021-02,USA-China,0.020157,6.4601,-0.001098,-0.153487936,-0.003344,0.007833
2,2021-03,USA-China,0.010724,6.5109,0.007833,-0.63106134,-0.009433,0.001182
3,2021-04,USA-China,0.014211,6.5186,0.001182,0.281525595,0.003487,-0.013359
4,2021-05,USA-China,0.009114,6.4321,-0.013359,-0.444211891,-0.005097,-0.001104
5,2021-06,USA-China,0.008897,6.4250,-0.001104,-0.024057627,-0.000217,0.007953

In [7]:
#model summary of sentiment and log exchange rate, lagged by 1 period
x = df[['Sentiment_Change']]

# Add constant (intercept) term
x = sm.add_constant(x)

# Dependent variable
y = df['Log_EXCHUS_Lag']

# Fit the OLS model
model = sm.OLS(y, x).fit()

# Print the summary
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         Log_EXCHUS_Lag   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.019
Method:                 Least Squares   F-statistic:                   0.03007
Date:                Tue, 05 Aug 2025   Prob (F-statistic):              0.863
Time:                        13:11:17   Log-Likelihood:                 155.68
No. Observations:                  52   AIC:                            -307.4
Df Residuals:                      50   BIC:                            -303.5
Df Model:                           1
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0020      0.002      1.181      0.243      -0.001       0.005
Sentiment_Change    -0.0285      0.164     -0.173      0.863      -0.359       0.302
==============================================================================
Omnibus:                        7.734   Durbin-Watson:                   1.183
Prob(Omnibus):                  0.021   Jarque-Bera (JB):                9.806
Skew:                           0.462   Prob(JB):                      0.00743
Kurtosis:                       4.917   Cond. No.                         96.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [25]:
#read in extra data from excel
df = pd.read_csv('data/multi_regression.csv', index_col = False)
df = df.dropna()
df.head()

,Month,Relation,Sentiment,EXCHUS,US_tariff_rate,China_tariff_rate,US_exports_millions,China_exports_millions,Trade_balance,Log_EXCHUS_Change,...,Log_EXCHUS_Change_Lag,US_log_tariff_rate_change_lag,China_log_tariff_rate_change_lag,Trade_balance_change_lag,Log_trade_balance_change_lag,US_log_exports_change_lag,China_log_exports_change_lag,US_log_exports_change,China_log_exports_change,Sentiment_change_lag
1,2021-02,USA-China,0.020157,6.4601,19.3,21.1,9265.1,33816.8,-24551.7,-0.001098,...,0.007833,0.0,0.0,-2570.3,-7.85,0.324128,0.166270,-0.339556,-0.138372,-0.009433
2,2021-03,USA-China,0.010724,6.5109,19.3,21.1,12812.0,39934.0,-27122.0,0.007833,...,0.001182,0.0,0.0,1682.3,7.43,-0.071209,-0.066330,0.324128,0.166270,0.003487
3,2021-04,USA-China,0.014211,6.5186,19.3,21.1,11931.4,37371.1,-25439.7,0.001182,...,-0.013359,0.0,0.0,-639.4,-6.46,0.039119,0.029410,-0.071209,-0.066330,-0.005097
4,2021-05,USA-China,0.009114,6.4321,19.3,21.1,12407.4,38486.5,-26079.1,-0.013359,...,-0.001104,0.0,0.0,-1557.6,-7.35,-0.021573,0.033039,0.039119,0.029410,-0.000217
5,2021-06,USA-China,0.008897,6.4250,19.3,21.1,12142.6,39779.3,-27636.7,-0.001104,...,0.007953,0.0,0.0,-896.9,-6.80,-0.032246,0.012779,-0.021573,0.033039,0.004191

In [27]:
#multivariate regression to check overall relationship
from statsmodels.multivariate.manova import MANOVA

# Define dependent variables (multiple)
dependent_vars = 'ExchangeRate + TariffRate + ExportValue'
dependent_vars = 'Log_EXCHUS_Change_Lag + US_log_tariff_rate_change_lag + China_log_tariff_rate_change_lag + Log_trade_balance_change_lag'

# Define independent variables
independent_vars = 'Sentiment_Change'

# Fit Multivariate Regression (MANOVA)
manova = MANOVA.from_formula(f'{dependent_vars} ~ {independent_vars}', data=df)
print(manova.mv_test())

                 Multivariate linear model
============================================================

------------------------------------------------------------
       Intercept        Value  Num DF  Den DF F Value Pr > F
------------------------------------------------------------
          Wilks' lambda 0.9270 4.0000 46.0000  0.9052 0.4688
         Pillai's trace 0.0730 4.0000 46.0000  0.9052 0.4688
 Hotelling-Lawley trace 0.0787 4.0000 46.0000  0.9052 0.4688
    Roy's greatest root 0.0787 4.0000 46.0000  0.9052 0.4688
------------------------------------------------------------

------------------------------------------------------------
    Sentiment_Change    Value  Num DF  Den DF F Value Pr > F
------------------------------------------------------------
          Wilks' lambda 0.9757 4.0000 46.0000  0.2869 0.8850
         Pillai's trace 0.0243 4.0000 46.0000  0.2869 0.8850
 Hotelling-Lawley trace 0.0249 4.0000 46.0000  0.2869 0.8850
    Roy's greatest root 0.0249 4.0000 46.0000  0.2869 0.8850
============================================================

In [29]:
#separate simple regressions for each dependent
x = sm.add_constant(df['Sentiment_Change'])

# Dependent variables
y1 = df['Log_EXCHUS_Change_Lag']
y2 = df['US_log_tariff_rate_change_lag']
y3 = df['China_log_tariff_rate_change_lag']
y4 = df['Log_trade_balance_change_lag']

# Separate regressions
model1 = sm.OLS(y1, x).fit()
model2 = sm.OLS(y2, x).fit()
model3 = sm.OLS(y3, x).fit()
model4 = sm.OLS(y4, x).fit()

# Print summaries
print(model1.summary())
print(model2.summary())
print(model3.summary())
print(model4.summary())

                              OLS Regression Results
=================================================================================
Dep. Variable:     Log_EXCHUS_Change_Lag   R-squared:                       0.000
Model:                               OLS   Adj. R-squared:                 -0.020
Method:                    Least Squares   F-statistic:                   0.01234
Date:                   Tue, 05 Aug 2025   Prob (F-statistic):              0.912
Time:                           13:32:48   Log-Likelihood:                 152.35
No. Observations:                     51   AIC:                            -300.7
Df Residuals:                         49   BIC:                            -296.8
Df Model:                              1
Covariance Type:               nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0022      0.002      1.240      0.221      -0.001       0.006
Sentiment_Change    -0.0185      0.167     -0.111      0.912      -0.353       0.316
==============================================================================
Omnibus:                        7.235   Durbin-Watson:                   1.184
Prob(Omnibus):                  0.027   Jarque-Bera (JB):                9.033
Skew:                           0.424   Prob(JB):                       0.0109
Kurtosis:                       4.879   Cond. No.                         95.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                                  OLS Regression Results
=========================================================================================
Dep. Variable:     US_log_tariff_rate_change_lag   R-squared:                       0.001
Model:                                       OLS   Adj. R-squared:                 -0.020
Method:                            Least Squares   F-statistic:                   0.02960
Date:                           Tue, 05 Aug 2025   Prob (F-statistic):              0.864
Time:                                   13:32:48   Log-Likelihood:                 11.255
No. Observations:                             51   AIC:                            -18.51
Df Residuals:                                 49   BIC:                            -14.65
Df Model:                                      1
Covariance Type:                       nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0193      0.028      0.695      0.490      -0.036       0.075
Sentiment_Change     0.4559      2.650      0.172      0.864      -4.869       5.781
==============================================================================
Omnibus:                       28.254   Durbin-Watson:                   2.091
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              532.461
Skew:                           0.246   Prob(JB):                    2.39e-116
Kurtosis:                      18.822   Cond. No.                         95.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                                   OLS Regression Results
============================================================================================
Dep. Variable:     China_log_tariff_rate_change_lag   R-squared:                       0.001
Model:                                          OLS   Adj. R-squared:                 -0.019
Method:                               Least Squares   F-statistic:                   0.05876
Date:                              Tue, 05 Aug 2025   Prob (F-statistic):              0.809
Time:                                      13:32:48   Log-Likelihood:                -16.901
No. Observations:                                51   AIC:                             37.80
Df Residuals:                                    49   BIC:                             41.67
Df Model:                                         1
Covariance Type:                          nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.0090      0.048      0.187      0.853      -0.088       0.106
Sentiment_Change     1.1157      4.602      0.242      0.809      -8.133      10.365
==============================================================================
Omnibus:                       49.157   Durbin-Watson:                   2.566
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1197.164
Skew:                           1.587   Prob(JB):                    1.09e-260
Kurtosis:                      26.522   Cond. No.                         95.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                                 OLS Regression Results
========================================================================================
Dep. Variable:     Log_trade_balance_change_lag   R-squared:                       0.021
Model:                                      OLS   Adj. R-squared:                  0.001
Method:                           Least Squares   F-statistic:                     1.070
Date:                          Tue, 05 Aug 2025   Prob (F-statistic):              0.306
Time:                                  13:32:48   Log-Likelihood:                -176.11
No. Observations:                            51   AIC:                             356.2
Df Residuals:                                49   BIC:                             360.1
Df Model:                                     1
Covariance Type:                      nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const               -0.5305      1.093     -0.485      0.630      -2.727       1.666
Sentiment_Change   108.0270    104.412      1.035      0.306    -101.797     317.851
==============================================================================
Omnibus:                     5714.274   Durbin-Watson:                   2.127
Prob(Omnibus):                  0.000   Jarque-Bera (JB):                7.487
Skew:                           0.202   Prob(JB):                       0.0237
Kurtosis:                       1.167   Cond. No.                         95.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.