In [1]:
import os
if not os.path.exists('exchange_rate_analysis'):
    !git clone https://github.com/matthewhirokawa/exchange_rate_analysis.git
%cd exchange_rate_analysis

"\nimport os\nif not os.path.exists('exchange_rate_analysis'):\n    !git clone https://github.com/matthewhirokawa/exchange_rate_analysis.git\n%cd exchange_rate_analysis\n"

In [2]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
monthly_sentiment_nltk = pd.read_csv('data/usa_china_extended_monthly_sentiment_nltk.csv')
#monthly_sentiment_nltk['Month'] = pd.to_datetime(monthly_sentiment_nltk['Month']).dt.to_period('M')

monthly_sentiment_textblob = pd.read_csv('data/usa_china_extended_monthly_sentiment_textblob.csv')
#monthly_sentiment_textblob['Month'] = pd.to_datetime(monthly_sentiment_textblob['Month']).dt.to_period('M')
monthly_sentiment_textblob.head()

     Month   Relation  Sentiment
0  2021-01  USA-China   0.023501
1  2021-02  USA-China   0.020157
2  2021-03  USA-China   0.010724
3  2021-04  USA-China   0.014211
4  2021-05  USA-China   0.009114

In [4]:
usd_cny_exchange_rate = pd.read_csv('data/usd_cny_monthly_exchange_rate_2021.csv')
#usd_cny_exchange_rate['Month'] = pd.to_datetime(usd_cny_exchange_rate['Month']).dt.to_period('M')
usd_cny_exchange_rate.head()

         DATE  EXCHUS    Month
0  2021-01-01  6.4672  2021-01
1  2021-02-01  6.4601  2021-02
2  2021-03-01  6.5109  2021-03
3  2021-04-01  6.5186  2021-04
4  2021-05-01  6.4321  2021-05

In [5]:
#combine dataframes, drop date keep month
combined_df_textblob = pd.merge(monthly_sentiment_textblob, usd_cny_exchange_rate, on = 'Month', how = 'inner')
combined_df_textblob = combined_df_textblob.drop(columns=['DATE'])
#combined_df_textblob.to_csv("combined_df_textblob.csv", index = False)
combined_df_textblob.head()

     Month   Relation  Sentiment  EXCHUS
0  2021-01  USA-China   0.023501  6.4672
1  2021-02  USA-China   0.020157  6.4601
2  2021-03  USA-China   0.010724  6.5109
3  2021-04  USA-China   0.014211  6.5186
4  2021-05  USA-China   0.009114  6.4321

In [8]:
#read in extra data from excel
df = pd.read_csv('data/multi_regression.csv', index_col = False)
df = df.dropna()
df.head()

,Month,Relation,Sentiment,EXCHUS,US_tariff_rate,China_tariff_rate,US_exports_millions,China_exports_millions,Trade_balance,Log_EXCHUS_Change,Sentiment_Change,Log_EXCHUS_Change_Lag,US_log_tariff_rate_change_lag,China_log_tariff_rate_change_lag,Log_trade_balance_change_lag
2,2021-03,USA-China,0.010724,6.5109,19.3,21.1,12812.0,39934.0,-27122.0,0.007833,-0.009433,-0.001098,0.0,0.0,-0.050527
3,2021-04,USA-China,0.014211,6.5186,19.3,21.1,11931.4,37371.1,-25439.7,0.001182,0.003487,0.007833,0.0,0.0,0.099564
4,2021-05,USA-China,0.009114,6.4321,19.3,21.1,12407.4,38486.5,-26079.1,-0.013359,-0.005097,0.001182,0.0,0.0,-0.064034
5,2021-06,USA-China,0.008897,6.4250,19.3,21.1,12142.6,39779.3,-27636.7,-0.001104,-0.000217,-0.013359,0.0,0.0,0.024823
6,2021-07,USA-China,0.013088,6.4763,19.3,21.1,11757.3,40290.9,-28533.6,0.007953,0.004191,-0.001104,0.0,0.0,0.058010

In [9]:
#multiple regression to check correlation
x = df[['Log_EXCHUS_Change_Lag', 'US_log_tariff_rate_change_lag', 'China_log_tariff_rate_change_lag', 'Log_trade_balance_change_lag']]
y = df['Sentiment_Change']

x = sm.add_constant(x)
model = sm.OLS(y, x).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       Sentiment_Change   R-squared:                       0.016
Model:                            OLS   Adj. R-squared:                 -0.070
Method:                 Least Squares   F-statistic:                    0.1849
Date:                Mon, 11 Aug 2025   Prob (F-statistic):              0.945
Time:                        10:46:53   Log-Likelihood:                 160.35
No. Observations:                  51   AIC:                            -310.7
Df Residuals:                      46   BIC:                            -301.0
Df Model:                           4
Covariance Type:            nonrobust
====================================================================================================
                                       coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------
const                               -0.0003      0.002     -0.155      0.877      -0.004       0.003
Log_EXCHUS_Change_Lag                0.0209      0.128      0.163      0.871      -0.237       0.279
US_log_tariff_rate_change_lag       -0.0073      0.021     -0.345      0.732      -0.050       0.035
China_log_tariff_rate_change_lag     0.0078      0.012      0.660      0.513      -0.016       0.031
Log_trade_balance_change_lag         0.0027      0.011      0.256      0.799      -0.019       0.024
==============================================================================
Omnibus:                       13.176   Durbin-Watson:                   3.130
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               16.137
Skew:                           0.932   Prob(JB):                     0.000313
Kurtosis:                       5.030   Cond. No.                         83.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.